### ISSUE TITLE
Copyright questions.

### ISSUE THREAD

**Issue by Wafelack** [Smart6502/cozen#4]
Hello, I was looking at your code and something made me think, why are the copyright notices set to « Abbix » ? Is it a previously used pseudo or something like that ?

E.g. https://github.com/Smart6502/cozen/blob/main/kernel/devices/video/font.h#L6

Regards,
Wafelack.

**Comment by Supercip971** [comment]
i think this is the guy who created this code, he removed/moved the old copyright

**Comment by Supercip971** [comment]
> i think this is the guy who created this code, he removed/moved the old copyright

dmca comin'

**Comment by rnbunker** [comment]
d m c a i n c o m i n g

**Comment by PhereloHD** [comment]
dmca teakedown incoming

**Comment by Keyboard-Slayer** [comment]
**FBI OPEN UP**
![image](https://user-images.githubusercontent.com/40356204/111513543-35d22f80-8751-11eb-952c-06edf649f1a1.png)

**Comment by DaimyoHub** [comment]
Hmm... I've seen a very similar project before. Same code, same arch, but not same copyright :thinking:.

**Comment by rnbunker** [comment]
https://github.com/abb1x/emerald

> Hmm... I've seen a very similar project before. Same code, same arch, but not same copyright . (dmca should fix that)

**Comment by Abb1x** [comment]
:thinking:

**Comment by PhereloHD** [comment]
get him down

**Comment by IdotMaster1** [comment]
DMCA takedown soon ™️ ©️

**Comment by Smart6502** [comment]
I only added names to files which I had changed the contents of
So now Im adding both names except for files solely created by me

**Comment by Smart6502** [comment]
> Hmm... I've seen a very similar project before. Same code, same arch, but not same copyright thinking. (dmca should fix that)

Fixed that lol

**Comment by Smart6502** [comment]
**Fixed it now**

**Comment by rnbunker** [comment]
s u r e

**Comment by PhereloHD** [comment]
a h y e s

**Comment by DamieFC** [comment]
How did this turn into a bunch of ridiculousness?
