### ISSUE TITLE
Device suggestions

### ISSUE THREAD

**Issue by DamieFC** [Smart6502/cozen#7]
I have a few suggestions for device support ("*drivers*"):
1. USB
2. Aux audio (I can't tell if it has it, I don't think so)
3. HDMI

I don't want to sound demanding but these would be nice to have 👍.

**Comment by Smart6502** [comment]
USB and HDMI and tricky, but Im planning on an Intel HDA driver for audio

**Comment by DamieFC** [comment]
Ok! Thanks! Should I just close this issue?
